### ISSUE TITLE
Cannot run builds or tests

### ISSUE THREAD

**Issue by Ryan-Gordon** [Verdagio/tsc-express-api#2]
Currently trying to run tests or a build but this is failing. 

It looks like some of the imports are incomplete. 

For tests: 
run `npm install`
and 
`npm run test`

Gives this output : 
<img width="681" alt="image" src="https://user-images.githubusercontent.com/11082710/53700941-d87c1780-3def-11e9-9c51-5e812eb59510.png">

But then running a build gives this output 

<img width="661" alt="image" src="https://user-images.githubusercontent.com/11082710/53700948-f47fb900-3def-11e9-89ec-57ab081398a8.png">

I have tried installing `@types/jasmine` which doesn't give success.

**Comment by Verdagio** [comment]
Appears that jasmine doesn't have a default export, even the @types/jasmine export doesn't work as expected. Temporarily removing as a dependency
